# Sprint14 Keras

# 【問題1】公式チュートリアルモデルを分担して実行
TensorFLowの公式チュートリアルモデルを分担して実行してください。


以下の中から1人ひとつ選び実行し、その結果を簡単に発表してください。

In [9]:
import tensorflow as tf
import tensorflow_datasets as tfds
import numpy as np
from sklearn.model_selection import train_test_split

In [2]:
mnist = tf.keras.datasets.mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10)
])

predictions = model(x_train[:1]).numpy()
predictions

11493376/11490434 [==============================] - 0s 0us/step


array([[-0.27040094, -0.14162745, -0.11076418, -0.5656812 , -0.14782846,
        -0.18261239,  0.8661366 ,  0.234083  ,  0.15451452, -0.5720195 ]],
      dtype=float32)

In [3]:
tf.nn.softmax(predictions).numpy()

array([[0.07508539, 0.08540455, 0.08808151, 0.05588778, 0.08487659,
        0.08197501, 0.23396312, 0.12435121, 0.11484017, 0.05553466]],
      dtype=float32)

In [4]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [5]:
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])

model.fit(x_train, y_train, epochs=5)
model.evaluate(x_test,  y_test, verbose=2)

probability_model = tf.keras.Sequential([
  model,
  tf.keras.layers.Softmax()
])

probability_model(x_test[:5])

Epoch 1/5
1875/1875 [==============================] - 5s 2ms/step - loss: 0.2957 - accuracy: 0.9142
Epoch 2/5
1875/1875 [==============================] - 5s 2ms/step - loss: 0.1402 - accuracy: 0.9590
Epoch 3/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.1033 - accuracy: 0.9691
Epoch 4/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.0859 - accuracy: 0.9736
Epoch 5/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.0752 - accuracy: 0.9765
313/313 - 0s - loss: 0.0778 - accuracy: 0.9764


<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[6.83950958e-08, 3.83515886e-09, 2.52698192e-06, 2.18831439e-04,
        4.15363854e-11, 2.74614571e-08, 4.53300557e-11, 9.99774992e-01,
        9.64551646e-07, 2.63555580e-06],
       [3.28834585e-06, 9.40279642e-05, 9.99610960e-01, 2.60531291e-04,
        4.58591532e-14, 6.57570070e-07, 6.74117018e-06, 2.76342803e-11,
        2.36859378e-05, 3.72776506e-12],
       [2.97720845e-07, 9.98968244e-01, 9.34516793e-05, 1.11787986e-05,
        3.99734563e-05, 1.31194665e-05, 3.84764053e-06, 7.38934148e-04,
        1.30227025e-04, 7.54881569e-07],
       [9.99798119e-01, 4.58486582e-11, 5.05689168e-05, 2.77113543e-07,
        5.98590987e-07, 1.86863269e-06, 1.17578275e-04, 2.84012403e-05,
        7.91009711e-08, 2.54984707e-06],
       [8.62236931e-08, 3.18676285e-09, 9.38494395e-07, 4.47826238e-08,
        9.99750435e-01, 1.81614396e-07, 2.09082054e-06, 6.00146304e-05,
        1.74694989e-07, 1.86110454e-04]], dtype=float32)>

# 【問題3】Iris（2値分類）をKerasで学習
TensorFlowによるIrisデータセットに対する2値分類をKerasに書き換えてください。

In [27]:
# データセットの読み込み
from sklearn.datasets import load_iris
iris_dataset = load_iris()

temp_X = iris_dataset.data
temp_y = iris_dataset.target.reshape(-1,1)

iris_marged = np.concatenate((temp_X, temp_y), axis=1)
iris_marged = iris_marged[iris_marged[:,4] >= 1]

iris_marged[:,4] = np.where(iris_marged[:,4] == 1, 0, 1)

X = iris_marged[:, :4].astype(np.float32)
y = iris_marged[:, 4]
y = y.astype(np.float32).reshape(-1,1)

# trainとtestに分割
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)
# さらにtrainとvalに分割
X_train, X_val, y_train, y_val = train_test_split(X_train, y_train, test_size=0.1, random_state=0)

In [28]:
#モデルの作成

hidden_layer_size = 50
output_size = 1

model = tf.keras.models.Sequential([
  tf.keras.layers.Dense(hidden_layer_size, activation='relu'),
  tf.keras.layers.Dense(hidden_layer_size, activation='relu'),
  tf.keras.layers.Dense(output_size)
])

predictions = model(X_train[:10]).numpy()
predictions

array([[0.17447832],
       [0.13758314],
       [0.0042426 ],
       [0.10882667],
       [0.03779012],
       [0.10127094],
       [0.10097942],
       [0.10359001],
       [0.14086369],
       [0.06115142]], dtype=float32)

In [29]:
tf.nn.sigmoid(predictions).numpy()

array([[0.54350924],
       [0.53434163],
       [0.50106066],
       [0.52717984],
       [0.5094464 ],
       [0.5252961 ],
       [0.52522343],
       [0.5258744 ],
       [0.5351578 ],
       [0.5152831 ]], dtype=float32)

In [30]:
loss_fn = tf.keras.losses.BinaryCrossentropy(from_logits=True)

In [ ]:
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])

model.fit(X_train, y_train, epochs=50)
model.evaluate(X_test,  y_test, verbose=2)

probability_model = tf.keras.Sequential([
  model,
  tf.keras.layers.Softmax()
])

probability_model(X_test)

# 【問題4】Iris（多値分類）をKerasで学習
TensorFlowによるIrisデータセットに対する3値分類をKerasに書き換えてください。

In [39]:
# データセットの読み込み
iris_dataset = load_iris()

X = iris_dataset.data.astype(np.float32)
y = iris_dataset.target.astype(np.int32)
y = np.identity(3)[y] #onehot

# trainとtestに分割
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)
# さらにtrainとvalに分割
X_train, X_val, y_train, y_val = train_test_split(X_train, y_train, test_size=0.2, random_state=0)

#モデルの作成

hidden_layer_size = 50
output_size = 3

model = tf.keras.models.Sequential([
  tf.keras.layers.Dense(hidden_layer_size, activation='relu'),
  tf.keras.layers.Dense(hidden_layer_size, activation='relu'),
  tf.keras.layers.Dense(output_size)
])

predictions = model(X_train[:10]).numpy()
predictions

array([[ 0.01027587, -1.2088268 , -0.2849437 ],
       [ 0.1617908 , -0.927117  , -0.04281303],
       [ 0.06292316, -1.4828999 , -0.49136028],
       [ 0.20209005, -0.849277  , -0.01313961],
       [-0.03789453, -1.1219807 , -0.33255863],
       [ 0.19354169, -1.4315438 , -0.46661496],
       [ 0.04606593, -1.2010453 , -0.30747554],
       [ 0.3753575 , -0.8803386 , -0.09497288],
       [ 0.03202066, -1.2656595 , -0.41123757],
       [ 0.37031236, -0.68482006, -0.21231055]], dtype=float32)

In [40]:
tf.nn.softmax(predictions).numpy()

array([[0.49022892, 0.1448603 , 0.36491078],
       [0.46478036, 0.15643759, 0.3787821 ],
       [0.5594029 , 0.1192291 , 0.3213679 ],
       [0.46386153, 0.16210091, 0.37403765],
       [0.48007852, 0.16236769, 0.35755372],
       [0.58354455, 0.11489691, 0.30155852],
       [0.5026312 , 0.14442284, 0.35294604],
       [0.52364975, 0.14917602, 0.32717416],
       [0.5221643 , 0.14263688, 0.33519888],
       [0.5244999 , 0.1826027 , 0.2928974 ]], dtype=float32)

In [41]:
loss_fn = tf.keras.losses.CategoricalCrossentropy(from_logits=True)

In [43]:
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])

model.fit(X_train, y_train, epochs=10)
model.evaluate(X_test,  y_test, verbose=2)

probability_model = tf.keras.Sequential([
  model,
  tf.keras.layers.Softmax()
])

probability_model(X_test)

Epoch 1/10
3/3 [==============================] - 0s 5ms/step - loss: 0.7739 - accuracy: 0.7917
Epoch 2/10
3/3 [==============================] - 0s 4ms/step - loss: 0.7260 - accuracy: 0.6875
Epoch 3/10
3/3 [==============================] - 0s 5ms/step - loss: 0.6794 - accuracy: 0.7500
Epoch 4/10
3/3 [==============================] - 0s 4ms/step - loss: 0.6405 - accuracy: 0.8646
Epoch 5/10
3/3 [==============================] - 0s 4ms/step - loss: 0.6052 - accuracy: 0.8646
Epoch 6/10
3/3 [==============================] - 0s 3ms/step - loss: 0.5730 - accuracy: 0.8646
Epoch 7/10
3/3 [==============================] - 0s 3ms/step - loss: 0.5441 - accuracy: 0.8646
Epoch 8/10
3/3 [==============================] - 0s 4ms/step - loss: 0.5177 - accuracy: 0.8854
Epoch 9/10
3/3 [==============================] - 0s 4ms/step - loss: 0.4928 - accuracy: 0.9062
Epoch 10/10
3/3 [==============================] - 0s 4ms/step - loss: 0.4730 - accuracy: 0.9167
1/1 - 0s - loss: 0.4897 - accuracy: 0.8

<tf.Tensor: shape=(30, 3), dtype=float32, numpy=
array([[0.02450736, 0.2512724 , 0.7242202 ],
       [0.13051595, 0.5292489 , 0.34023508],
       [0.87235796, 0.08458792, 0.04305409],
       [0.01958506, 0.29928365, 0.6811313 ],
       [0.8085096 , 0.13052432, 0.06096604],
       [0.01366477, 0.1890066 , 0.7973286 ],
       [0.831895  , 0.11381109, 0.05429385],
       [0.09264383, 0.496326  , 0.41103014],
       [0.08232472, 0.51183134, 0.40584394],
       [0.14138512, 0.517657  , 0.3409578 ],
       [0.02775975, 0.28738517, 0.6848551 ],
       [0.1047105 , 0.477874  , 0.41741544],
       [0.07686611, 0.43989658, 0.48323736],
       [0.0850741 , 0.49341276, 0.4215131 ],
       [0.07227653, 0.42483377, 0.50288975],
       [0.835274  , 0.10843322, 0.05629288],
       [0.08056643, 0.43597573, 0.48345786],
       [0.07597917, 0.40599585, 0.51802504],
       [0.76689225, 0.16413026, 0.06897743],
       [0.85635465, 0.09716795, 0.0464774 ],
       [0.03328173, 0.28350756, 0.68321073],
      

# 【問題5】House PricesをKerasで学習
TensorFlowによるHouse Pricesデータセットに対する回帰をKerasに書き換えてください。

In [46]:
#データ読み込み
import pandas as pd
from sklearn.preprocessing import StandardScaler

df = pd.read_csv('drive/My Drive/data/house-prices-advanced-regression-techniques_train.csv')
X = df[['GrLivArea', 'YearBuilt']].values
y = df['SalePrice'].values.reshape(-1,1)


scaler = StandardScaler()
X = scaler.fit_transform(X)

# trainとtestに分割
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)
# さらにtrainとvalに分割
X_train, X_val, y_train, y_val = train_test_split(X_train, y_train, test_size=0.2, random_state=0)


#モデルの作成
hidden_layer_size = 50
output_size = 1

model = tf.keras.models.Sequential([
  tf.keras.layers.Dense(hidden_layer_size, activation='relu'),
  tf.keras.layers.Dense(hidden_layer_size, activation='relu'),
  tf.keras.layers.Dense(output_size)
])

predictions = model(X_train[:10]).numpy()
predictions

array([[-0.15471107],
       [-0.03475707],
       [-0.12483937],
       [-0.03581494],
       [-0.11866688],
       [-0.06218399],
       [-0.01945069],
       [-0.28150588],
       [-0.05530083],
       [-0.02901087]], dtype=float32)

In [50]:
tf.keras.metrics.mean_squared_error(y_train[:10], predictions).numpy()

array([1.9432403e+10, 1.6900008e+10, 6.9765784e+10, 3.5607704e+10,
       3.2400044e+10, 6.4157377e+10, 4.4100006e+10, 1.6900073e+10,
       6.5025032e+10, 2.8561011e+10], dtype=float32)

In [52]:
loss_fn = tf.keras.losses.MeanSquaredError()

In [64]:
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['mse'])

model.fit(X_train, y_train, epochs=50)
model.evaluate(X_test,  y_test, verbose=2)

probability_model = tf.keras.Sequential([
  model,
  #何もいらない？
])

Y_pred = probability_model(X_test)
np.concatenate((Y_pred[:10], y_test[:10]), axis=1)

Epoch 1/50
30/30 [==============================] - 0s 2ms/step - loss: 8706276352.0000 - mse: 8706276352.0000
Epoch 2/50
30/30 [==============================] - 0s 1ms/step - loss: 8378416128.0000 - mse: 8378416128.0000
Epoch 3/50
30/30 [==============================] - 0s 1ms/step - loss: 8057304064.0000 - mse: 8057304064.0000
Epoch 4/50
30/30 [==============================] - 0s 2ms/step - loss: 7741607936.0000 - mse: 7741607936.0000
Epoch 5/50
30/30 [==============================] - 0s 1ms/step - loss: 7435552768.0000 - mse: 7435552768.0000
Epoch 6/50
30/30 [==============================] - 0s 1ms/step - loss: 7141898752.0000 - mse: 7141898752.0000
Epoch 7/50
30/30 [==============================] - 0s 2ms/step - loss: 6852344832.0000 - mse: 6852344832.0000
Epoch 8/50
30/30 [==============================] - 0s 1ms/step - loss: 6573233664.0000 - mse: 6573233664.0000
Epoch 9/50
30/30 [==============================] - 0s 2ms/step - loss: 6304993792.0000 - mse: 6304993792.0000
E

array([[238549.546875 , 200624.       ],
       [118285.5234375, 133000.       ],
       [ 98515.5546875, 110000.       ],
       [218430.578125 , 192000.       ],
       [114451.6484375,  88000.       ],
       [150364.21875  ,  85000.       ],
       [207582.65625  , 282922.       ],
       [105475.6796875, 141000.       ],
       [619109.0625   , 745000.       ],
       [165768.375    , 148800.       ]])

# 【問題6】MNISTをKerasで学習
TensorFlowによるMNISTデータセットによる画像の多値分類をKerasに書き換えてください。

In [87]:
# データセットの読み込み
from keras.datasets import mnist
from sklearn.preprocessing import OneHotEncoder

(X_train, y_train), (X_test, y_test) = mnist.load_data()

X_train = X_train.reshape(-1, 784).astype(np.float32)
X_test = X_test.reshape(-1, 784).astype(np.float32)

enc = OneHotEncoder(handle_unknown='ignore', sparse=False)
y_train_one_hot = enc.fit_transform(y_train[:, np.newaxis])
y_test_one_hot = enc.transform(y_test[:, np.newaxis])

X_train, X_val, y_train, y_val = train_test_split(X_train, y_train, test_size=0.2)


#モデルの作成
hidden_layer_size = 400
output_size = 10

model = tf.keras.models.Sequential([
  tf.keras.layers.Dense(hidden_layer_size, activation='relu'),
  tf.keras.layers.Dense(hidden_layer_size, activation='relu'),
  tf.keras.layers.Dense(output_size)
])

predictions = model(X_train[:1]).numpy()
predictions

array([[-32.280983,  39.455044, -64.82447 ,   9.51247 ,  29.124895,
         32.603252,  -7.758602,  56.715958,  42.017834,  73.65127 ]],
      dtype=float32)

In [88]:
tf.nn.softmax(predictions).numpy()

array([[0.0000000e+00, 1.4085378e-15, 0.0000000e+00, 1.3959688e-28,
        4.5966465e-20, 1.4896126e-18, 4.4070122e-36, 4.4166008e-08,
        1.8271493e-14, 1.0000000e+00]], dtype=float32)

In [89]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [90]:
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])

model.fit(X_train, y_train, epochs=5)
model.evaluate(X_val, y_val, verbose=2)

probability_model = tf.keras.Sequential([
  model,
  tf.keras.layers.Softmax()
])

probability_model(X_test)

Epoch 1/5
1500/1500 [==============================] - 9s 6ms/step - loss: 1.7589 - accuracy: 0.8970
Epoch 2/5
1500/1500 [==============================] - 9s 6ms/step - loss: 0.2337 - accuracy: 0.9464
Epoch 3/5
1500/1500 [==============================] - 9s 6ms/step - loss: 0.1860 - accuracy: 0.9539
Epoch 4/5
1500/1500 [==============================] - 9s 6ms/step - loss: 0.1668 - accuracy: 0.9560
Epoch 5/5
1500/1500 [==============================] - 8s 6ms/step - loss: 0.1506 - accuracy: 0.9605
375/375 - 1s - loss: 0.2056 - accuracy: 0.9522


<tf.Tensor: shape=(10000, 10), dtype=float32, numpy=
array([[2.4016486e-15, 4.2149853e-07, 6.0415657e-12, ..., 9.9999952e-01,
        4.6774192e-16, 2.5000732e-08],
       [1.9457752e-22, 7.4526753e-07, 9.9999928e-01, ..., 4.2541665e-21,
        1.6525301e-22, 8.2582514e-30],
       [2.5252283e-13, 9.9999988e-01, 4.6491461e-08, ..., 3.6899067e-11,
        1.6378300e-07, 6.0370500e-09],
       ...,
       [2.1089735e-21, 4.2566059e-13, 4.3624284e-25, ..., 6.9599856e-16,
        6.1871705e-14, 1.1417062e-09],
       [1.1510468e-06, 6.5251402e-07, 2.0511654e-07, ..., 8.9066243e-06,
        1.0721552e-04, 5.4971722e-05],
       [1.1588753e-14, 7.1259916e-15, 2.5048990e-09, ..., 3.2026125e-23,
        2.6332465e-12, 5.7135779e-19]], dtype=float32)>